version: 2.1

jobs:
  Demo:

    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Demo-Test"
          command: "while true; do echo yes; sleep 30; done"

workflows:
  Demo:
    jobs:
      - Demo
